import os


# KEYCLOAK
KEYCLOAK_PROTOCOL = os.environ.get("KEYCLOAK_PROTOCOL", "http")
KEYCLOAK_HOST = os.environ.get("KEYCLOAK_HOST", "keycloak")
KEYCLOAK_PORT = os.environ.get("KEYCLOAK_PORT", "")
KEYCLOAK_REDIRECT_PROTOCOL = os.environ.get("KEYCLOAK_REDIRECT_PROTOCOL", None)
KEYCLOAK_REDIRECT_HOST = os.environ.get("KEYCLOAK_REDIRECT_HOST", None)
KEYCLOAK_REDIRECT_PORT = os.environ.get("KEYCLOAK_REDIRECT_PORT", None)
KEYCLOAK_REALM = os.environ.get("KEYCLOAK_REALM", "avataa")
KEYCLOAK_CLIENT_ID = os.environ.get("KEYCLOAK_CLIENT_ID", "frontend-settings")
KEYCLOAK_CLIENT_SECRET = os.environ.get("KEYCLOAK_CLIENT_SECRET", None)

if KEYCLOAK_REDIRECT_PROTOCOL is None:
    KEYCLOAK_REDIRECT_PROTOCOL = KEYCLOAK_PROTOCOL
if KEYCLOAK_REDIRECT_HOST is None:
    KEYCLOAK_REDIRECT_HOST = KEYCLOAK_HOST
if KEYCLOAK_REDIRECT_PORT is None:
    KEYCLOAK_REDIRECT_PORT = KEYCLOAK_PORT

KEYCLOAK_URL = f"{KEYCLOAK_PROTOCOL}://{KEYCLOAK_HOST}"
if KEYCLOAK_PORT:
    KEYCLOAK_URL += f":{KEYCLOAK_PORT}"
KEYCLOAK_PUBLIC_KEY_URL = f"{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}"
KEYCLOAK_REDIRECT_URL = (
    f"{KEYCLOAK_REDIRECT_PROTOCOL}://{KEYCLOAK_REDIRECT_HOST}"
)
if KEYCLOAK_REDIRECT_PORT:
    KEYCLOAK_REDIRECT_URL += f":{KEYCLOAK_REDIRECT_PORT}"
KEYCLOAK_TOKEN_URL = f"{KEYCLOAK_REDIRECT_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/token"
KEYCLOAK_AUTHORIZATION_URL = f"{KEYCLOAK_REDIRECT_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/auth"


# OPA
OPA_PROTOCOL = os.environ.get("OPA_PROTOCOL", "http")
OPA_HOST = os.environ.get("OPA_HOST", "opa")
OPA_PORT = os.environ.get("OPA_PORT", "8181")
OPA_POLICY = os.environ.get("OPA_POLICY", "main")

OPA_URL = f"{OPA_PROTOCOL}://{OPA_HOST}:{OPA_PORT}"
OPA_POLICY_PATH = f"/v1/data/{OPA_POLICY}"


# OTHER
SECURITY_TYPE = os.environ.get("SECURITY_TYPE", "DISABLE").upper()
ADMIN_ROLE = "__admin"


# CACHE
SECURITY_MIDDLEWARE_PROTOCOL = os.environ.get(
    "SECURITY_MIDDLEWARE_PROTOCOL", KEYCLOAK_PROTOCOL
)
SECURITY_MIDDLEWARE_HOST = os.environ.get(
    "SECURITY_MIDDLEWARE_HOST", KEYCLOAK_HOST
)
SECURITY_MIDDLEWARE_PORT = os.environ.get(
    "SECURITY_MIDDLEWARE_PORT", KEYCLOAK_PORT
)
if (
    SECURITY_MIDDLEWARE_HOST == KEYCLOAK_HOST
    and SECURITY_MIDDLEWARE_PORT == KEYCLOAK_PORT
):
    SECURITY_POSTFIX = (
        f"/realms/{KEYCLOAK_REALM}/protocol/openid-connect/userinfo"
    )
else:
    SECURITY_POSTFIX = f"/api/security_middleware/v1/cached/realms/{KEYCLOAK_REALM}/protocol/openid-connect/userinfo"
SECURITY_MIDDLEWARE_URL = f"{SECURITY_MIDDLEWARE_PROTOCOL}://{SECURITY_MIDDLEWARE_HOST}:{SECURITY_MIDDLEWARE_PORT}{SECURITY_POSTFIX}"
