"""color_range_2bool_added

Revision ID: 02db1c4b60e7
Revises: e827cdb8d4c5
Create Date: 2023-10-13 11:08:06.784275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02db1c4b60e7'
down_revision = 'e827cdb8d4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_range', sa.Column('with_indeterminate', sa.Boolean(), nullable=True))
    op.add_column('color_range', sa.Column('with_cleared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color_range', 'with_cleared')
    op.drop_column('color_range', 'with_indeterminate')
    # ### end Alembic commands ###
