"""tmo_id

Revision ID: 060957ed9336
Revises: dd25e5da3b85
Create Date: 2023-05-02 12:32:13.875451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060957ed9336'
down_revision = 'dd25e5da3b85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE table_columns CASCADE')
    op.add_column('table_columns', sa.Column('tmo_id', sa.Integer(), nullable=False))
    op.drop_constraint('table_columns_name_created_by_sub_key', 'table_columns', type_='unique')
    op.create_unique_constraint(None, 'table_columns', ['tmo_id', 'name', 'created_by_sub'])
    op.execute('TRUNCATE TABLE table_filters CASCADE')
    op.add_column('table_filters', sa.Column('tmo_id', sa.Integer(), nullable=False))
    op.drop_constraint('table_filters_name_created_by_sub_public_default_key', 'table_filters', type_='unique')
    op.create_unique_constraint(None, 'table_filters', ['tmo_id', 'name', 'created_by_sub', 'public', 'default'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_filters', type_='unique')
    op.create_unique_constraint('table_filters_name_created_by_sub_public_default_key', 'table_filters', ['name', 'created_by_sub', 'public', 'default'])
    op.drop_column('table_filters', 'tmo_id')
    op.drop_constraint(None, 'table_columns', type_='unique')
    op.create_unique_constraint('table_columns_name_created_by_sub_key', 'table_columns', ['name', 'created_by_sub'])
    op.drop_column('table_columns', 'tmo_id')
    # ### end Alembic commands ###
