"""fix

Revision ID: 1f4a714a370d
Revises: 5a13361e9ec0
Create Date: 2023-08-28 23:28:45.716003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4a714a370d'
down_revision = '5a13361e9ec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_set', sa.Column('join_operator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_set', 'join_operator')
    # ### end Alembic commands ###
