"""Added module_settings_log table

Revision ID: 24fd466c28c2
Revises: ac22cf6984ad
Create Date: 2024-08-01 16:31:43.144169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fd466c28c2'
down_revision = 'ac22cf6984ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_settings_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module'], ['modules.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_settings_logs_modification_date'), 'module_settings_logs', ['modification_date'], unique=False)
    op.drop_constraint('module_settings_module_fkey', 'module_settings', type_='foreignkey')
    op.create_foreign_key(None, 'module_settings', 'modules', ['module'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module_settings', type_='foreignkey')
    op.create_foreign_key('module_settings_module_fkey', 'module_settings', 'modules', ['module'], ['name'])
    op.drop_index(op.f('ix_module_settings_logs_modification_date'), table_name='module_settings_logs')
    op.drop_table('module_settings_logs')
    # ### end Alembic commands ###
