"""range_unique_new

Revision ID: 59fc2f621fba
Revises: ea6506666b2c
Create Date: 2023-12-15 10:06:53.431254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59fc2f621fba'
down_revision = 'ea6506666b2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('color_range_unique', 'color_range', type_='unique')
    op.create_unique_constraint('color_range_unique', 'color_range', ['tmo_id', 'tprm_id', 'name', 'created_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('color_range_unique', 'color_range', type_='unique')
    op.create_unique_constraint('color_range_unique', 'color_range', ['tmo_id', 'tprm_id', 'val_type', 'name', 'created_by'])
    # ### end Alembic commands ###
