"""state

Revision ID: 5b549c80ddae
Revises: b2efe2f8c72a
Create Date: 2023-07-19 15:30:34.742582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b549c80ddae'
down_revision = 'b2efe2f8c72a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.CheckConstraint('expire_date >= creation_date', name='exp_qe_cr'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_id'), 'state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_id'), table_name='state')
    op.drop_table('state')
    # ### end Alembic commands ###
