"""add hidden column for filterset

Revision ID: 8101a8328142
Revises: 909a5bdc5b16
Create Date: 2024-03-25 13:03:58.068869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8101a8328142'
down_revision = '909a5bdc5b16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_set', sa.Column('hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_set', 'hidden')
    # ### end Alembic commands ###
