"""create module settings table

Revision ID: 97670ddeaf99
Revises: ed4433f18551
Create Date: 2023-12-11 15:36:22.995284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97670ddeaf99'
down_revision = 'ed4433f18551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_settings',
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['module'], ['modules.name'], ),
    sa.PrimaryKeyConstraint('module')
    )
    op.alter_column('color_range', 'direction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('color_range', 'direction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('module_settings')
    # ### end Alembic commands ###
