"""Changed column names for module_settings_log table

Revision ID: a7c006bc4b22
Revises: 24fd466c28c2
Create Date: 2024-08-12 16:36:31.529215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7c006bc4b22'
down_revision = '24fd466c28c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('module_settings_logs_module_fkey', 'module_settings_logs', type_='foreignkey')
    op.drop_index('ix_module_settings_logs_modification_date', table_name='module_settings_logs')
    op.alter_column('module_settings_logs', 'module', new_column_name='domain')
    op.alter_column('module_settings_logs', 'field_name', new_column_name='variable')
    op.alter_column('module_settings_logs', 'modified_by', new_column_name='user')
    op.alter_column('module_settings_logs', 'modification_date', new_column_name='change_time')
    op.create_index(op.f('ix_module_settings_logs_change_time'), 'module_settings_logs', ['change_time'], unique=False)
    op.create_foreign_key('module_settings_logs_module_fkey', 'module_settings_logs', 'modules', ['domain'], ['name'],
                          ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('module_settings_logs_module_fkey', 'module_settings_logs', type_='foreignkey')
    op.drop_index(op.f('ix_module_settings_logs_change_time'), table_name='module_settings_logs')
    op.alter_column('module_settings_logs', 'domain', new_column_name='module')
    op.alter_column('module_settings_logs', 'variable', new_column_name='field_name')
    op.alter_column('module_settings_logs', 'user', new_column_name='modified_by')
    op.alter_column('module_settings_logs', 'change_time', new_column_name='modification_date')
    op.create_foreign_key('module_settings_logs_module_fkey', 'module_settings_logs', 'modules', ['module'], ['name'],
                          ondelete='CASCADE')
    op.create_index('ix_module_settings_logs_modification_date', 'module_settings_logs', ['modification_date'],
                    unique=False)
    # ### end Alembic commands ###
