"""user settings

Revision ID: ac22cf6984ad
Revises: 8101a8328142
Create Date: 2024-06-21 15:47:36.609822

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ac22cf6984ad'
down_revision = '8101a8328142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('settings', sa.JSON(), nullable=False),
                    sa.PrimaryKeyConstraint('username', 'key', name='user_settings_pkey')
                    )
    op.create_index('user_settings_key_username_index', 'user_settings', ['username', 'key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_settings_key_username_index', table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
