"""Added order and pinned columns for table_columns.

Revision ID: ad6f395091ed
Revises: 99c15b94fcc0
Create Date: 2023-08-21 08:06:09.092752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Inspector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad6f395091ed'
down_revision = '99c15b94fcc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn.engine)
    tables = inspector.get_table_names()
    if 'permission_table_filters' in tables:
        op.drop_table('permission_table_filters')
    if 'settings_table' in tables:
        op.drop_table('settings_table')
    if 'permission_table_columns' in tables:
        op.drop_table('permission_table_columns')
    if 'permission_map' in tables:
        op.drop_table('permission_map')
    op.add_column('table_columns', sa.Column('order', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('table_columns', sa.Column('pinned', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn.engine)
    tables = inspector.get_table_names()

    op.drop_column('table_columns', 'pinned')
    op.drop_column('table_columns', 'order')
    if 'permission_map' not in tables:
        op.create_table('permission_map',
        sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('permission', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('create', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('update', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['map.id'], name='permission_map_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='permission_map_pkey')
        )
    if 'permission_table_columns' not in tables:
        op.create_table('permission_table_columns',
        sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('permission', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('create', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('update', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['table_columns.id'], name='permission_table_columns_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='permission_table_columns_pkey')
        )
    if 'settings_table' not in tables:
        op.create_table('settings_table',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='settings_table_pkey'),
        sa.UniqueConstraint('name', name='settings_table_name_key')
        )
    if 'permission_table_filters' not in tables:
        op.create_table('permission_table_filters',
        sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('permission', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('create', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('update', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['table_filters.id'], name='permission_table_filters_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='permission_table_filters_pkey')
        )
    # ### end Alembic commands ###
