"""add tmo info with priority

Revision ID: df966d97f63d
Revises: 1f4a714a370d
Create Date: 2023-08-29 12:50:03.627670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'df966d97f63d'
down_revision = '1f4a714a370d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_set', sa.Column('tmo_info', sa.JSON(), nullable=False,
                                          server_default='{}'))
    op.add_column('filter_set', sa.Column('priority', sa.Integer(), nullable=False,
                                          server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_set', 'priority')
    op.drop_column('filter_set', 'tmo_info')
    # ### end Alembic commands ###
