"""new_colors

Revision ID: e827cdb8d4c5
Revises: df966d97f63d
Create Date: 2023-09-05 14:52:37.931833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e827cdb8d4c5'
down_revision = 'df966d97f63d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmo_id', sa.String(), nullable=False),
    sa.Column('tprm_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('ranges', sa.JSON(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_by_sub', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmo_id', 'tprm_id', 'name', 'created_by')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_range')
    # ### end Alembic commands ###
