"""range_val_type

Revision ID: ea6506666b2c
Revises: 97670ddeaf99
Create Date: 2023-12-14 15:59:35.809927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea6506666b2c'
down_revision = '97670ddeaf99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_range', sa.Column('val_type', sa.String(), server_default='float', nullable=False))
    op.drop_constraint('color_range_tmo_id_tprm_id_name_created_by_key', 'color_range', type_='unique')
    op.create_unique_constraint('color_range_unique', 'color_range', ['tmo_id', 'tprm_id', 'val_type', 'name', 'created_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('color_range_unique', 'color_range', type_='unique')
    op.create_unique_constraint('color_range_tmo_id_tprm_id_name_created_by_key', 'color_range', ['tmo_id', 'tprm_id', 'name', 'created_by'])
    op.drop_column('color_range', 'val_type')
    # ### end Alembic commands ###
