"""Added direction

Revision ID: ed4433f18551
Revises: 02db1c4b60e7
Create Date: 2023-10-30 12:24:52.638785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4433f18551'
down_revision = '02db1c4b60e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color_range', sa.Column('direction', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color_range', 'direction')
    # ### end Alembic commands ###
